language: java

dist: trusty

jdk:
  - oraclejdk11
  - oraclejdk-ea
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk-ea

jobs:
  include:
    - stage: deploy # generate gh-pages after all builds succeeded
      install: skip # we don't need the jdks for the generation of gh-pages
      script:
        - gem install asciidoctor --version 1.5.8
        - ./build_gh-pages.sh

